### ISSUE TITLE
the gui renders only the last game frame

### ISSUE THREAD

**Issue by oaken-source** [oaken-source/noobcraft#3]
the view is not updated before the script has finished - we need some asynchronous update mechanism to render the game process.

**Comment by Feinbube** [comment]
the gui is updated every 20ms. (50 fps) don't you think that is fast enough?

**Comment by oaken-source** [comment]
this was fixed in c3b2a4937a135b41ed1c7893b9053a59e302f280

**Comment by Feinbube** [comment]
:D
